/**
 * Photo → tonal ASCII converter for the four "AI und Organisation" cards.
 *
 * Reads source photos from web/art-src/, resizes each to a character grid
 * (correcting for the ~0.5 glyph aspect so the image isn't stretched), maps
 * luminance to a density ramp, and writes the four strings to
 * src/data/aiArt.ts as static data. Tonal shading carries the 3D depth.
 *
 * Run:  node scripts/img2ascii.mjs
 *
 * Drop the sources in web/art-src/ named by slot (any of .jpg/.jpeg/.png/.webp):
 *   processes.*   -> AI in Prozessen     (the blue building apex)
 *   human.*       -> AI und Mensch       (the marble head)
 *   decision.*    -> AI in Entscheidungen(the handshake)
 *   structure.*   -> AI und Strukturen   (Centre Pompidou)
 */

import sharp from 'sharp'
import { readdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const HERE = dirname(fileURLToPath(import.meta.url))
const SRC = join(HERE, '..', 'art-src')
const OUT = join(HERE, '..', 'src', 'data', 'aiArt.ts')

const COLS = 92 // characters wide; height derives from each image's aspect
const GLYPH_ASPECT = 0.5 // charW / charH — squash rows so circles stay round
const RAMP = " .'^\":;~-=+ox*#%@" // sparse (dark) -> dense (bright); dense = brighter on black

// Per-slot tone controls. invert flips so dark subjects read bright; the
// gamma/contrast bring the form out of a flat photo.
const SLOTS = [
  // apex: invert so the dark building reads bright and the sky falls to black
  { key: 'processes', invert: true, gamma: 1.1, contrast: 1.2 },
  { key: 'human', invert: false, gamma: 1.2, contrast: 1.3 },
  // handshake is a dark photo — lift the midtones hard so the hands come out
  { key: 'decision', invert: false, gamma: 1.75, contrast: 1.45 },
  { key: 'structure', invert: false, gamma: 1.1, contrast: 1.25 },
]

function findFile(key) {
  const hit = readdirSync(SRC).find((f) => f.toLowerCase().startsWith(key + '.'))
  return hit ? join(SRC, hit) : null
}

async function toAscii(path, opt) {
  const meta = await sharp(path).metadata()
  const rows = Math.max(1, Math.round(COLS * (meta.height / meta.width) * GLYPH_ASPECT))
  let img = sharp(path).resize(COLS, rows, { fit: 'fill' }).grayscale().normalize()
  if (opt.contrast && opt.contrast !== 1) img = img.linear(opt.contrast, -(128 * (opt.contrast - 1)))
  if (opt.gamma && opt.gamma !== 1) img = img.gamma(opt.gamma)
  const { data } = await img.raw().toBuffer({ resolveWithObject: true })
  const lines = []
  for (let y = 0; y < rows; y++) {
    let line = ''
    for (let x = 0; x < COLS; x++) {
      let l = data[y * COLS + x] / 255
      if (opt.invert) l = 1 - l
      line += RAMP[Math.max(0, Math.min(RAMP.length - 1, Math.round(l * (RAMP.length - 1))))]
    }
    lines.push(line.replace(/\s+$/, ''))
  }
  return lines.join('\n')
}

const out = {}
for (const slot of SLOTS) {
  const file = findFile(slot.key)
  if (!file) {
    console.warn(`! missing source for "${slot.key}" — put ${slot.key}.<jpg|png> in web/art-src/`)
    continue
  }
  out[slot.key] = await toAscii(file, slot)
  console.log(`✓ ${slot.key}: ${out[slot.key].split('\n').length} rows from ${file.split('/').pop()}`)
}

const order = ['processes', 'human', 'decision', 'structure']
const arr = order.map((k) => JSON.stringify(out[k] ?? ''))
const body = `// GENERATED by scripts/img2ascii.mjs — do not edit by hand.
// Order: 0 Prozesse · 1 Mensch · 2 Entscheidungen · 3 Strukturen
export const AI_ART: readonly string[] = [
  ${arr.join(',\n  ')},
]
`
writeFileSync(OUT, body)
console.log(`\nWrote ${OUT}`)
